seed: 0
trainer:
  accelerator: auto
  fast_dev_run: False
  logger: False
model:
  class_path: rlaihf.algorithms.SkyworkLlama
  init_args:
    model_name_or_path: "Skywork/Skywork-Reward-Llama-3.1-8B-v0.2"
    model_dtype: float16
    save_dir: "results/chatbot-arena_skywork"
    dialog_keys: ["conversation_a", "conversation_b"]
    label_key: "score"
data:
  class_path: rlaihf.datamodules.ChatBotArenaCorrEvalDatamodule
  init_args:
    load_dataset_name: "lmsys/chatbot_arena_conversations"
    load_dataset_split: "train"
    tokenize_pipeline:
      class_path: rlaihf.tokenize_pipelines.TokenizePipelineV2
      init_args:
        model_name_or_path: "Ray2333/GRM-Gemma-2B-sftreg"
        raw_data_convert: rlaihf.data_conversion.ChatBotArenaTrainDataConversion
    collate_fn:
      class_path: rlaihf.collators.StandardPaddingCollatorV3
      init_args:
        other_keys: ["score", "id", "model_a", "model_b"]
    batch_size: 4
    save_dataset_dir: "~/datasets"
    num_workers: 1
    holdout_model_id: 0 # Change in script
    keep_tie: True

