seed: 0
trainer:
  accelerator: auto
  fast_dev_run: False
  logger: False
model:
  class_path: rlaihf.algorithms.GrmGemma
  init_args:
    # model_name_or_path: "/home/zhaoyiz/projects/misc/rm_finetune/results/GRM-Gemma-2B-sftreg/run_20241222_152817"
    model_name_or_path: "Ray2333/GRM-Gemma-2B-sftreg"
    model_dtype: float16
    save_dir: "/home/zhaoyiz/projects/data/reward_dicts/mt-bench_gemma_sorted_avg"
    dialog_keys: ["conversation_a", "conversation_b"]
data:
  class_path: rlaihf.datamodules.MtbenchTestDatamodule
  init_args:
    load_dataset_name: "lmsys/mt_bench_human_judgments"
    load_dataset_split: "human"
    tokenize_pipeline:
      class_path: rlaihf.tokenize_pipelines.TokenizePipelineV2
      init_args:
        raw_data_convert: rlaihf.data_conversion.MtbenchSortedDataConversionV2
    collate_fn:
      class_path: rlaihf.collators.StandardPaddingCollatorV3
      init_args:
        other_keys: ["score", "id", "model_a", "model_b"]
    batch_size: 4
    save_dataset_dir: "~/datasets"
    num_workers: 2

